version: '3.8'  # Specify the version of Docker Compose syntax being used

services:  # Define the services that compose the application

  # Service for the MySQL database
  vprodb:
    image: saduasar/vprofiledb:v2  # Use a specific Docker image for the database
    build:
      context: ./Docker-files/db  # Build the image using Dockerfile in the specified context
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306 for MySQL connections
    volumes:
      - vprodbdata:/var/lib/mysql  # Mount a volume to persist MySQL data
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass  # Set environment variable for MySQL root password

  # Service for Memcached
  vprocache01:
    image: memcached  # Use the official Memcached Docker image
    ports:
      - "11211:11211"  # Map host port 11211 to container port 11211 for Memcached connections

  # Service for RabbitMQ
  vpromq01:
    image: rabbitmq  # Use the official RabbitMQ Docker image
    ports:
      - "15672:15672"  # Map host port 15672 to container port 15672 for RabbitMQ management UI
    environment:
      - RABBITMQ_DEFAULT_USER=test  # Set default username for RabbitMQ management
      - RABBITMQ_DEFAULT_PASS=test  # Set default password for RabbitMQ management

  # Service for the application
  vproapp:
    image: saduasar/vprofileapp:v2  # Use a specific Docker image for the application
    build:
      context: ./Docker-files/app  # Build the image using Dockerfile in the specified context
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080 for accessing the application
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps  # Mount a volume for application data

  # Service for the web server
  vproweb:
    image: saduasar/vprofileweb:latest  # Use a specific Docker image for the web server
    build:
      context: ./Docker-files/web  # Build the image using Dockerfile in the specified context
    ports:
      - "80:80"  # Map host port 80 to container port 80 for accessing the web server

volumes:
  vprodbdata: {}  # Define a named volume for MySQL data
  vproappdata: {}  # Define a named volume for application data

